% Example 9.4 (pag. 483)
% This script resolves example 9.5:
% Lead Controller Design, from the book:
% Nise, Norman S., Control System Engineering, 
% 6th ed. 2011, John Wiley & Sons, Inc. 
%
% This requires the user to edit the first few lines containing the 'num'
% and 'den' variables, which refer to the plant's transfer function for
% which the PID is being designed.
%
% Note that following example 9.5, the Proportional Controller is designed
% first to obtain its peak time. This value is then reduced by 2/3 for the
% PID design.
%
% The rest of the program, with the exception of the variables 'num' and
% 'den', is interactive.
% 
% Several RL graphical windows will open; the user must zoom in on the
% region of interest, guided by the messages generated by this script
% during its execution.
%
% Fernando Passold, reviewed in 14.06.2021, 01/06/2026

format compact
format shortg
disp('Routine to assist in the design of a PID Controller.')
disp('Based on script ch9p2.m, example 9.5 from de book:');
disp('Nise, Norman S., Control System Engineering,');
disp('6th ed. 2011, John Wiley & Sons, Inc.'); 

% It is recommended to execute the following two lines:
clear all % deletes all previous variables
close all % close all previous figures

% Edit the lines below to specify the numerator and denominator of the
% plant's transfer function. 
% num=[1 8]; 
% den=poly([-3 -6 -10]);
num = 72;
den = poly([-2 -6 -12]);

g=tf(num,den);
disp('Plant to be compensated:')
zpk(g)

OS=input('Maximum tolerated overshoot percentage (%OS): ? ');
% calculando zeta
zeta=(-log(OS/100))/(sqrt(pi*pi+(log(OS/100))^2));
fprintf('Corresponding damping factor (zeta): %g\n\n', zeta)

disp("Plotting the plant's RL diagram for proportional controller design.")
fig = figure(); rlocus(g)
sgrid(zeta,0)
title(['Proportional Controller Project (%OS=', num2str(OS), '%)'])

disp('Proportional Controller Tuning:')
fprintf('Look at Figure %d: ', fig.Number)
disp('Do a zoom over the area of interest and press any bottom to continue...')
disp (' ')
pause

% First graphical window: RL for proportional controller tuning
% selecting a point in RL...
figure(fig.Number); % refocus on the correct window
[k,poles]=rlocfind(g);

fprintf('\nBased on the tuned Proportional Controller:\n')
% Calculando t_s original...
t_s=4/abs(real(poles(2)));
fprintf('Estimated settiling time: %g\n', t_s)

t_p=pi/abs(imag(poles(2)));
fprintf('Estimated peak time: %g\n', t_p)

disp(' ')
disp('Starting the PD Project Phase:')
disp('Calculating new t_p = (previous t_p)*2/3...')
new_t_p=t_p*2/3;
fprintf('New peak time: t_p = %g\n', new_t_p)
theta=acos(zeta);
fprintf('\nCalculating the guide line angle relative to the desired zeta (prop. %OS)...\n')
fprintf('theta (cos(zeta)): %.2f^o\n', theta*180/pi)
% theta*180/pi  % remember that MATLAB works in rad...
fprintf('180^o - theta = %.2f^o\n\n', 180-theta*180/pi)

disp('Determining the real and imaginary parts for desired poles of MF...')
new_wd = pi/new_t_p;
% fprintf('Desired imaginary part of dominant pole (system compensated): %g\n', new_omega)
new_sigma = -new_wd/tan(theta);
% fprintf('Desired real part of dominant pole (system compensated): %g\n', new_sigma)
fprintf ('Desired MF poles at: s = %g ± j%g\n\n', new_sigma, new_wd )
clear j % in case varible j was previous used with a for loop
desired_MF_poles=[new_sigma+j*new_wd];

disp('Opening another graphical window showing RL with desired position for MF poles...')
fig = figure; 
rlocus(g); hold on; sgrid(zeta,0);
plot(real(desired_MF_poles), imag(desired_MF_poles),'mx')
plot(real(desired_MF_poles),-imag(desired_MF_poles),'mx')
plot([real(desired_MF_poles) 0], [imag(desired_MF_poles) imag(desired_MF_poles)], 'm:')
plot([real(desired_MF_poles) real(desired_MF_poles)], [imag(desired_MF_poles) -imag(desired_MF_poles)], 'm:')
plot([real(desired_MF_poles) 0], [-imag(desired_MF_poles) -imag(desired_MF_poles)], 'm:')
msg=num2str(new_sigma,'%.2f');
msg1=[msg ' ± j' num2str(new_wd,'%.2f')];
text(real(desired_MF_poles), imag(desired_MF_poles), msg1);

fprintf('Figure %g shows the RL + desired MF poles associated with the PD design.\n\n', fig.Number);
% title('RL + Desired location of dominant pole (PD compensation phase):')
title('RL + Desired MF Poles (PD Stage)')

% Considering the summary of angles...
% Sum(th_ceros)-Sum(th_polos)=180*(2*i+1)

open_poles=roots(den);
[num_poles aux2]=size(open_poles);
sum=0;
disp ('Calculating angle Contribution of poles of the open loop system:')

% Third window: shows the result of the angular contribution calculations.
% Plots the RL graph and overlay the angular informations on the graph.
fig = figure();
pzmap(g); hold on; sgrid(zeta, 0);
plot(real(desired_MF_poles), imag(desired_MF_poles),'ms')
plot(real(desired_MF_poles),-imag(desired_MF_poles),'ms')
plot([real(desired_MF_poles) 0],[imag(desired_MF_poles) imag(desired_MF_poles)],'m:')
plot([real(desired_MF_poles) real(desired_MF_poles)],[imag(desired_MF_poles) -imag(desired_MF_poles)],'m:')
plot([real(desired_MF_poles) 0],[-imag(desired_MF_poles) -imag(desired_MF_poles)],'m:')
text(real(desired_MF_poles), imag(desired_MF_poles), msg1);

% calculates the angular contribution of each pole
for i=1:num_poles
    % open_poles(i)
    x(i)= new_sigma - real(open_poles(i)); % -new_sigma - real(open_poles(i));
    y(i)= new_wd;
    th(i) = atan2(y(i),x(i)); % determinando contribuicao de cada polo
    sum = sum + th(i);
    % th(i)*180/pi
    % fprintf('No. Pole : Pole : Angle Contribution\n')
    fprintf('\tp(%1g) = %g\t--> %3.2f^o\n', i,open_poles(i),th(i)*180/pi)
    % Updating the graph with angular information of the poles
    plot([real(open_poles(i)) new_sigma], [imag(open_poles(i)) new_wd],'c:')
    msg = num2str( th(i)*180/pi, '%.2f');
    msg = [msg '^o'];
    text(real(open_poles(i))*1.05, imag(open_poles(i))*1.05, msg)
end
fprintf('Sum of the angular contributions of the poles: %.2f^o\n', sum*180/pi)

% Considering the zeros of the plant
zeros=roots(num);
[num_zeros aux2]=size(zeros);
if num_zeros>0
    fprintf ('\nCalculating angle Contribution of zeros of the open loop system:\n')
    for i=1:num_zeros
        x(i) = new_sigma - real(zeros(i)); % -new_sigma - real(zeros(i));
        y(i) = new_wd;
        th(i) = atan2(y(i),x(i));
        sum = sum - th(i);
        fprintf('\tz(%1i) = %g\t--> %3.2f^o\n', i, zeros(i), th(i)*180/pi)
        % Updating the graph with angular information of the poles
        plot([real(zeros(i)) new_sigma], [imag(zeros(i)) new_wd],'g:')
        msg = num2str( th(i)*180/pi, '%.2f');
        msg = [msg '^o'];
        text(real(zeros(i))*1.05, imag(zeros(i))*1.05, msg)
    end
end

fprintf('\nSum of total angular contributions: %.2f^o\n', sum*180/pi)
final_angle = abs(pi-sum);
fprintf('Final Resulting angle for the PD zero: %.2f^o\n', final_angle*180/pi)
zc = -new_sigma - new_wd/tan(final_angle); 
fprintf('\nPosition of the zero of the PD: in s =%g\n', zc)

% Plot the line down to the zero of the PD (result of the angular
% contribution).
plot(zc,0, 'ro') %
plot([zc new_sigma], [0 new_wd],'r:');
msg=num2str((final_angle*180/pi),'%.2f');
msg=[msg '^o'];
text( zc*1.05, 0.05, msg)
text( zc*1.05, -new_wd*0.15, 'z_{PD}')
title('Contributing angles (PD compensation phase):')
fprintf('Figure %d shows the angular contributions and position found for the zero of the PD.\n', fig.Number);
xlim([zc*1.05 2])
axis equal

% PD transfer function
num_c=[1 -zc];
den_c=1;
c=tf(num_c,den_c);
disp('PD controller equation (without general gain):')
% zpk(c)
fprintf('\n\tC_{PD}(s) = (s + %g)\n\n', -zc);
% Adding PD to the direct loop equation
cg=series(g,c); % the same as: cg=c*g

disp('PD Tuning Stage:')
fig = figure;
rlocus(cg); hold on; sgrid(zeta,0);
title('RL for the system with the PD');
% plotting desired poles of MF
plot( [new_sigma new_sigma], [new_wd -new_wd], 'ms')
text(real(desired_MF_poles), imag(desired_MF_poles), msg1);
msg = ['t_p=' num2str(new_t_p, '%.2f')];
text(new_sigma*1.075, -new_wd-0.075, msg)
text( zc*1.05, -new_wd*0.15, 'z_{PD}')

fprintf('Figure %d shows the direct-loop RL of the system with the PD.\n', fig.Number);
disp('Do a zoom over the area of interest and press any bottom to continue...')
pause

figure(fig.Number); % ensuring focus on the correct window
[K_pd,poles_pd]=rlocfind(cg);
title('RL of system + PD (1st-stage design)')

PD = K_pd*c;
fprintf('\nComplete PD equation:\n')
% zpk(PD)
fprintf('\n\tC_{PD}(s) = %g (s + %g)\n\n', K_pd, -zc);

disp('Closing the loop with the chosen gain for the PD...')
fprintf('Desired t_p = %g, checking t_p reached:\n', new_t_p)
t_pd=feedback(K_pd*cg,1); % original FTMF variable adopted by NISE (PD Controller)
t_g=feedback(k*g,1); % Original FTMF variable adopted by NISE (Proportional Controller)
fig = figure;
step(t_g,t_pd) % ltiview(t_g,t_pd)
legend ('Prop.', 'PD');
stepinfo(t_pd)
fprintf('\nFigure %d shows the MF step response obtained with the PD and Proportional Controllers.\n\n', fig.Number);

fprintf('Final step --> adding PI action:\n')
zero_PI = -0.5; % value originally determined by NISE
% At this point in the code, NISE could have incorporated other angular
% contribution calculations to accurately determine the position of the
% zero of PI.
% Faster PI => zero PI == slowest pole of the plant
zero_PI = max(pole(g));
fprintf ('Select a position for the zero of PI,\nbetween %g <= s < 0) [%g]', min(pole(g)), zero_PI);
desired_MF_poles = input (': ? ');
if ~(isempty(desired_MF_poles))
    zero_PI = desired_MF_poles;
end
num_PID=conv([1 -zc],[1 -zero_PI]); % Note that the zero of PD is already being considered.
den_PID=([1 0]);
PID=tf(num_PID,den_PID);
fprintf('\nPID transfer function (without overall gain):\n')
% zpk(PID)
msg=['K (s+' num2str(-zc) ') (s+' num2str(-zero_PI) ')' ];
u=length(msg);
fprintf('\n             %s\n', msg);
msg = repmat('-', 1, u);
fprintf  ('C_{PID}(s) = %s\n', msg);
msg = repmat(' ', 1, round(u/2)-1);
fprintf  ('             %ss\n\n', msg);

% deducing FTMA(s) with PID
PIDg=PID*g;
disp('PID + Plant transfer function:')
zpk(PIDg)

fig = figure(); 
rlocus(PIDg); hold on; zgrid(zeta,0)
% plotando polos desejados de MF
plot([new_sigma new_sigma],[new_wd -new_wd],'m*')
title('RL FTMA(s): PID + plant')
disp('PID overall gain tuning:');
fprintf ('Figure %d shows the RL of PID + plant (for PID tuning)...\n', fig.Number);
disp('Do a zoom over the area of interest and press any bottom to continue...')
pause

figure(fig.Number); 
[k_PIDg,poles_PIDg]=rlocfind(PIDg);

fprintf('\nFinal (complete) equation of the PID (variable "PID2"):\n');
PID2 = k_PIDg*PID;
zpk(PID2)
[num_PID,den_PID] = tfdata(PID2, 'v');
Kp = num_PID(2);
Ki = num_PID(3);
Kd = num_PID(1);
fprintf('\tK_p = %g\n', Kp);
fprintf('\tK_i = %g\n', Ki);
fprintf('\tK_d = %g\n', Kd);

t_PIDg=feedback(k_PIDg*PIDg,1); % closing the loop with PID
% disp('Sistema PID + Planta, lazo cerrado:')
% zpk(t_PIDg)

fig = figure();  
step (t_g,t_pd,t_PIDg); % ltiview(t_g,t_pd,t_PIDg)
legend('Prop.', 'PD', 'PID');
fprintf('\nFigure %d shows the MF response to a step input obtained for the controllers.\n\n', fig.Number)
stepinfo(t_PIDg)
